---
- name: Update NAT Forwarding Rule on Gateway Server
  hosts: servers
  become: yes

  tasks:
    - name: Copy the NAT controller script to the server
      copy:
        src: "{{ nat_script_path }}"
        dest: /tmp/nat_controller.py
        mode: '0755'

    - name: Execute the NAT script with the chosen target IP
      command: "python3 /tmp/nat_controller.py {{ target_ip }}"